theme: jekyll-theme-minimal
title: Cold Electricity Open Project
description: Cold Electricity Open Project - A sustainable energy open project aiming to popularize cold electricity and its generators for global use. We welcome all forms of collaboration.
